steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/useful-memory-464107-d6/nuevo-youtobe',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/useful-memory-464107-d6/nuevo-youtobe'
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'nuevo-youtobe',
        '--image',
        'gcr.io/useful-memory-464107-d6/nuevo-youtobe',
        '--region',
        'europe-west1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port',
        '8080'
      ]
images:
  - 'gcr.io/useful-memory-464107-d6/nuevo-youtobe'

