name: Sync YouTube videos to GCS

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # Se ejecuta todos los días a las 2am UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp google-cloud-storage

      - name: Run sync script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          python sync_youtube_to_bucket.py
